version: 2.1

jobs:
  test:
    parameters:
      gemfile:
        type: string
      ruby-image:
        type: string
    docker:
      - image: << parameters.ruby-image >>
    environment:
      BUNDLE_GEMFILE: << parameters.gemfile >>
    working_directory: ~/sbpayment.rb
    steps:
      - checkout
      - run: gem update bundler
      - run: bundle config set --local path vendor/bundle
      - run: bundle check || bundle install --jobs=4 --retry=3
      - run: bundle exec rspec

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              gemfile:
                - gemfiles/faraday-0.16/Gemfile
                - gemfiles/faraday-0.17/Gemfile
                - gemfiles/faraday-1.0/Gemfile
                - gemfiles/faraday-1.4/Gemfile
                - gemfiles/faraday-1.5/Gemfile
              ruby-image:
                - circleci/ruby:2.6.7-browsers
                - circleci/ruby:2.7.3-browsers
                - circleci/ruby:3.0.2-browsers
                - circleci/ruby:latest-browsers
